const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(dist, 'data.js'), 'utf8'), context);
const data = JSON.parse(JSON.stringify(context.window.CASEBOOK));
const core = require('../dist/core.js');
const source = fs.readFileSync(path.join(root, '../sources/upstream-README.md'), 'utf8');
const rows = source.split(/\r?\n/).filter(line => /^\|\s*\d+\s*\|/.test(line));
assert.equal(data.articles.length, rows.length, '上游条目完整性');
assert.equal(data.articles.length, 343);
assert.equal(new Set(data.articles.map(a => a.id)).size, 343);
assert.equal(new Set(data.articles.map(a => a.company)).size, 39);
assert.equal(data.articles.filter(a => a.review).length, 6);
for (const [index, a] of data.articles.entries()) {
  assert.ok(rows[index].includes('[' + a.title + '](' + a.url + ')'), '保留原始标题和链接 ' + a.id);
  assert.match(a.guide, /[\u4e00-\u9fff]/, '每条具备中文导读');
  assert.ok(['https:', 'http:'].includes(new URL(a.url).protocol));
  assert.ok(a.topics.every(t => data.topics[t]));
  assert.equal(a.evidence, a.review ? 'reviewed' : 'guide');
  if (a.review) for (const key of ['summary','problem','approach','result','tradeoff','takeaway','sourceSection','checkedAt']) assert.ok(a.review[key], '总结依据完整 ' + a.id);
}
const base = { query: '', company: '', topic: '', evidence: '', sort: 'recommended' };
const query = fields => core.filterArticles(data, { ...base, ...fields });
assert.equal(query({ evidence: 'reviewed' }).length, 6);
assert.equal(query({ evidence: 'guide' }).length, 337);
assert.ok(query({ query: '缓存' }).length > 0, '中文查询');
assert.ok(query({ query: 'POSTGRES notion' }).length > 0, '大小写与多词查询');
assert.ok(query({ query: 'Postgres', company: 'Notion' }).every(a => a.company === 'Notion'));
assert.equal(query({ company: 'Canva', evidence: 'reviewed' }).length, 2);
assert.equal(query({ topic: 'Caching', evidence: 'reviewed' })[0].id, '081');
assert.equal(query({ query: '不存在的XYZ案例' }).length, 0);
assert.equal(query({ company: 'Discord', topic: 'Payments' }).length, 0);
const oldest = query({ sort: 'oldest' });
assert.ok(oldest.every((a, i) => !i || a.year >= oldest[i-1].year));
const newest = query({ sort: 'newest' });
assert.ok(newest.every((a, i) => !i || a.year <= newest[i-1].year));
assert.ok(query({}).slice(0,6).every(a => a.review));
const original = query({ sort: 'source' });
const ids = [];
for (let page = 1; page <= Math.ceil(original.length / 12); page++) ids.push(...core.paginate(original, page, 12).items.map(a => a.id));
assert.deepEqual(ids, original.map(a => a.id), '跨页不遗漏、不重复');
assert.equal(core.paginate(original, 1000, 12).page, 29);
assert.equal(core.paginate([], 5, 12).items.length, 0);
assert.equal(core.escapeHTML('<script>"&'), '&lt;script&gt;&quot;&amp;');
for (const name of ['app.js','core.js','data.js']) new vm.Script(fs.readFileSync(path.join(dist, name), 'utf8'), { filename: name });
const html = fs.readFileSync(path.join(dist, 'index.html'), 'utf8');
for (const [, url] of html.matchAll(/(?:src|href)="([^"]+)"/g)) {
  if (/^(?:https?:|#)/.test(url)) continue;
  assert.ok(fs.existsSync(path.resolve(dist, url)), '本地资源存在 ' + url);
}
const idsInHTML = [...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);
assert.equal(idsInHTML.length, new Set(idsInHTML).size, 'HTML id 唯一');
const manifest = JSON.parse(fs.readFileSync(path.join(root, '.openai/hosting.json'), 'utf8'));
assert.equal(manifest.static.directory, 'dist');
console.log('通过：343 条来源对应、中文导读、6 篇总结依据、组合筛选、搜索、排序、分页、转义、JS 语法和页面资源。');
