const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'dist');
const pages=[['understanding.md','index.html','从照片到三维'],['principles.md','principles.html','六条技术路线'],['implementation.md','implementation.html','3DGS 如何实现'],['comparison.md','comparison.html','产品与框架对比'],['chatgpt.md','chatgpt.html','ChatGPT 的已知与未知'],['applications.md','applications.html','应用、扩展与验证'],['notes.md','notes.html','来源与研究记录']].filter(p=>fs.existsSync(path.join(root,p[0])));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function inline(s){const tokens=[];const save=x=>`\u0001${tokens.push(x)-1}\u0002`;s=s.replace(/`([^`]+)`/g,(_,x)=>save(`<code>${esc(x)}</code>`));s=s.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,(_,a,u)=>save(`<img src="${esc(u)}" alt="${esc(a)}" ${u.endsWith(".png")?'width="1536" height="1024"':'width="1200" height="580"'} loading="lazy">`));s=s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,a,u)=>{const mapped=pages.find(p=>u.split('#')[0]===p[0]);if(mapped)u=mapped[1]+(u.includes('#')?'#'+u.split('#').slice(1).join('#'):'');if(!mapped&&!/^https?:/.test(u)&&fs.existsSync(path.join(root,u.split('#')[0])))u='documents/'+u;return save(`<a href="${esc(u)}"${u.startsWith('https:')?' rel="noreferrer"':''}>${esc(a)}</a>`)});s=esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');return s.replace(/\u0001(\d+)\u0002/g,(_,n)=>tokens[n]);}
function render(md){const lines=md.replace(/\r/g,'').split('\n'),html=[],heads=[];let i=0;const row=l=>l.trim().replace(/^\||\|$/g,'').split('|').map(x=>x.trim());while(i<lines.length){let l=lines[i];if(!l.trim()){i++;continue}if(l.startsWith('```')){const buf=[];i++;while(i<lines.length&&!lines[i].startsWith('```'))buf.push(lines[i++]);i++;html.push(`<pre><code>${esc(buf.join('\n'))}</code></pre>`);continue}const h=l.match(/^(#{1,4}) (.+)$/);if(h){const id='section-'+(heads.length+1);heads.push({level:h[1].length,id,text:h[2]});html.push(`<h${h[1].length} id="${id}">${inline(h[2])}</h${h[1].length}>`);i++;continue}if(l.startsWith('|')&&/^\|[ :|-]+\|\s*$/.test(lines[i+1]||'')){const header=row(l);i+=2;const rows=[];while(i<lines.length&&lines[i].startsWith('|'))rows.push(row(lines[i++]));html.push(`<div class="table-wrap" tabindex="0" role="region" aria-label="${esc(header.join('、'))}对比表"><table><thead><tr>${header.map(x=>`<th scope="col">${inline(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${inline(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`);continue}if(/^(?:- |\d+\. )/.test(l)){const ordered=/^\d/.test(l),items=[];while(i<lines.length&&new RegExp(ordered?'^\\d+\\. ':'^- ').test(lines[i]))items.push(lines[i++].replace(/^(?:- |\d+\. )/,''));html.push(`<${ordered?'ol':'ul'}>${items.map(x=>`<li>${inline(x)}</li>`).join('')}</${ordered?'ol':'ul'}>`);continue}if(l.startsWith('> ')){html.push(`<blockquote>${inline(l.slice(2))}</blockquote>`);i++;continue}const buf=[l];i++;while(i<lines.length&&lines[i].trim()&&!/^(#|\||-|\d+\. |>|```)/.test(lines[i]))buf.push(lines[i++]);html.push(`<p>${inline(buf.join(' '))}</p>`)}return {html:html.join('\n'),heads};}
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(path.join(out,'assets'),{recursive:true});fs.mkdirSync(path.join(out,'documents'),{recursive:true});
fs.copyFileSync(path.join(__dirname,'src/style.css'),path.join(out,'style.css'));fs.cpSync(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});
fs.cpSync(path.join(root,'assets'),path.join(out,'documents/assets'),{recursive:true});fs.mkdirSync(path.join(out,'documents/app'),{recursive:true});fs.copyFileSync(path.join(__dirname,'README.md'),path.join(out,'documents/app/README.md'));
for(const name of fs.readdirSync(root).filter(x=>x.endsWith('.md')||x==='validation.json'||x==='sources.json'||x==='upstream.json'||x==='UPSTREAM-LICENSE.txt'))fs.copyFileSync(path.join(root,name),path.join(out,'documents',name));
for(let n=0;n<pages.length;n++){const [file,url,label]=pages[n],md=fs.readFileSync(path.join(root,file),'utf8'),{html,heads}=render(md),title=heads[0]?.text||label;const toc=heads.filter(h=>h.level===2).map(h=>`<a href="#${h.id}">${esc(h.text)}</a>`).join('');const page=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · 三维重建研究</title><meta name="description" content="多角度照片如何通过 3DGS 生成可交互三维效果：输入、实现原理、输出，以及摄影测量、NeRF、神经表面、几何预测、生成式三维和同类产品对比。"><link rel="stylesheet" href="style.css"></head><body><a class="skip" href="#main">跳到正文</a><aside class="side"><a class="brand" href="index.html">照片 → 三维</a><div class="eyebrow">GAUSSIAN SPLATTING · 研究 012</div><nav aria-label="研究章节">${pages.map(p=>`<a href="${p[1]}"${url===p[1]?' aria-current="page"':''}>${p[2]}</a>`).join('')}</nav><div class="status">资料核查：2026-09-11<br>官方库未在本机训练<br>网页为中文研究手册<br><a href="https://github.com/graphdeco-inria/gaussian-splatting">查看原始仓库 ↗</a></div></aside><main class="shell" id="main"><div class="topbar"><span>三维表示 · 实现原理 · 产品对照</span><a href="documents/${file}" download>下载本章 Markdown ↓</a></div><article>${html.replace(/(<\/h1>)/,'$1'+`<nav class="toc" aria-label="本章目录">${toc}</nav>`)}<nav class="pager" aria-label="前后章节">${n>0?`<a href="${pages[n-1][1]}">← ${pages[n-1][2]}</a>`:'<span></span>'}${n<pages.length-1?`<a href="${pages[n+1][1]}">${pages[n+1][2]} →</a>`:''}</nav></article><footer class="footer"><span>本地整理与技术判断按证据标注；产品功能随版本变化。</span><a href="https://github.com/yydshly/0911_codex_project">研究总仓库</a></footer></main></body></html>`;fs.writeFileSync(path.join(out,url),page);}
console.log(`Built ${pages.length} reading pages in ${out}`);
