'use strict';
const data=window.DRAMA_DATA;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const entryButtons=document.querySelector('#entry-buttons');
data.routes.forEach((r,i)=>{const b=document.createElement('button');b.textContent=r[0];b.dataset.route=i;b.setAttribute('aria-pressed','false');entryButtons.append(b);});
function route(i){const r=data.routes[i];entryButtons.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));document.querySelector('#route-result').innerHTML=`<strong>${esc(r[1])}</strong><p>${esc(r[2])}</p><p class="muted">${esc(r[3])}</p>`;}
entryButtons.addEventListener('click',e=>{const b=e.target.closest('button[data-route]');if(b)route(Number(b.dataset.route));});route(0);
function selectCase(id){
 const c=data.cases[id];
 document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.case===id)));
 document.querySelector('#case-content').innerHTML=`<div class="case-intro"><span class="status ${id==='shuihu'?'warn':''}">${esc(c.status)}</span><h3 style="margin-top:18px">${esc(c.title)}</h3><p class="seed">“${esc(c.seed)}”</p><p class="case-description">${esc(c.description)}</p></div><figure class="result-figure"><a href="${c.image}" target="_blank" rel="noopener"><img src="${c.image}" alt="${esc(c.imageAlt)}" loading="lazy"></a><figcaption>${esc(c.caption)}</figcaption></figure><p class="result-note">${esc(c.note)}</p><h3>60 秒目标 / 六镜推进</h3><ol class="shot-list">${c.shots.map((s,i)=>`<li><b>${String(i+1).padStart(2,'0')} / ${i*10}—${(i+1)*10} 秒</b>${esc(s)}</li>`).join('')}</ol><div class="step-grid">${c.steps.map(s=>`<section class="step"><small>关联技能：${esc(s.skill)}</small><h3>${esc(s.title)}</h3><p>${esc(s.effect)}</p>${s.docs.map(d=>`<button class="doc-button" data-doc="${esc(d[1])}">${esc(d[0])} ↗</button>`).join('')}</section>`).join('')}</div><div class="trace"><h3>${esc(c.traceTitle)}</h3><p>${esc(c.trace)}</p></div>`;
}
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>selectCase(b.dataset.case)));selectCase('empty-room');
document.querySelector('#skill-grid').innerHTML=data.skills.map((s,i)=>`<details><summary>${String(i+1).padStart(2,'0')} · ${esc(s.title)}</summary><span class="skill-code"><a target="_blank" rel="noopener" href="https://github.com/zenstory-ai/drama-skills/blob/${data.version}/skills/${s.id}/SKILL.md">${s.id} ↗</a></span><p><strong>输入：</strong>${esc(s.input)}</p><p><strong>工作：</strong>${esc(s.action)}</p><p><strong>产出：</strong>${esc(s.output)}</p><p class="muted">${esc(s.boundary)}</p></details>`).join('');
// A small escaped Markdown reader. Source HTML is never executed; unsupported syntax remains readable text.
function markdown(text,base){
 const inline=s=>esc(s).replace(/!?\[([^\]]+)\]\(([^\s)]+)\)/g,(_,label,url)=>{let href;try{href=new URL(url.replace(/&amp;/g,'&'),base).href;}catch{return label;}return /^https?:/.test(href)?`<a href="${esc(href)}" target="_blank" rel="noopener">${label}</a>`:label;}).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
 const lines=text.replace(/\r/g,'').split('\n');let out='',para=[],list=[],table=[],code=null;
 const flush=()=>{if(para.length){out+='<p>'+para.map(inline).join('<br>')+'</p>';para=[];}if(list.length){out+='<ul>'+list.map(s=>'<li>'+inline(s)+'</li>').join('')+'</ul>';list=[];}if(table.length){const rows=table.filter(s=>!/^\|[\s:|\-]+\|?$/.test(s));out+='<div class="table-wrap"><table>'+rows.map((s,i)=>'<tr>'+s.replace(/^\||\|$/g,'').split('|').map(c=>`<${i?'td':'th'}>${inline(c.trim())}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table></div>';table=[];}};
 for(const l of lines){if(/^```/.test(l)){if(code!==null){out+='<pre>'+esc(code.join('\n'))+'</pre>';code=null;}else{flush();code=[];}continue;}if(code!==null){code.push(l);continue;}if(!l.trim()){flush();continue;}const h=l.match(/^(#{1,6})\s+(.*)/);if(h){flush();out+=`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`;continue;}if(l.startsWith('|')){if(para.length||list.length)flush();table.push(l);continue;}if(table.length)flush();const li=l.match(/^\s*(?:[-*]|\d+\.)\s+(.*)/);if(li){if(para.length)flush();list.push(li[1]);continue;}if(list.length)flush();if(l.startsWith('>')){flush();out+='<blockquote>'+inline(l.replace(/^>\s?/,''))+'</blockquote>';continue;}para.push(l);}flush();if(code!==null)out+='<pre>'+esc(code.join('\n'))+'</pre>';return out;
}
const reader=document.querySelector('#reader');let activeDoc=null;
document.querySelector('#case-content').addEventListener('click',e=>{const b=e.target.closest('[data-doc]');if(!b)return;activeDoc=data.docs[b.dataset.doc];document.querySelector('#reader-title').textContent=activeDoc.title;document.querySelector('#reader-body').innerHTML=b.dataset.doc.endsWith('.jsonl')?'<pre>'+esc(activeDoc.text)+'</pre>':markdown(activeDoc.text,activeDoc.url);document.querySelector('#reader-source').href=activeDoc.url;document.querySelector('#copy-status').textContent='';reader.showModal();reader.scrollTop=0;});
document.querySelector('#reader-close').addEventListener('click',()=>reader.close());
document.querySelector('#copy-doc').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(activeDoc.text);document.querySelector('#copy-status').textContent='已复制全文';}catch{document.querySelector('#copy-status').textContent='复制未成功，可选中文字复制或打开原文件。';}});
