const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const modulePath=process.env.PLAYWRIGHT_MODULE||'playwright';
const {chromium}=require(modulePath);
const app=path.resolve(__dirname,'..'),root=path.join(app,'dist'),out=path.join(root,'evidence/screenshots');fs.mkdirSync(out,{recursive:true});
const tests=[],screenshots=[],errors=[];
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(app,f))).digest('hex');
const fileNames=['dist/app.js','dist/index.html','dist/styles.css','dist/catalog.js','dist/validator.js','dist/fixtures.js','scripts/browser-check.cjs'];
const beforeHashes=Object.fromEntries(fileNames.map(f=>[f,hash(f)]));
async function main(){const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1024},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
async function test(name,fn){try{await fn();tests.push({name,status:'passed'});}catch(e){tests.push({name,status:'failed',error:e.message});}}
async function snap(file,label){await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:path.join(out,file),fullPage:true});screenshots.push({path:'evidence/screenshots/'+file,label});}
try{
await page.goto('http://127.0.0.1:4312/',{waitUntil:'networkidle'});
await test('首页展示技能执行四环节和三层实现',async()=>{assert.equal(await page.locator('.flow-node').count(),4);assert.equal(await page.locator('.layer').count(),3);await snap('overview.png','桌面：技能原理与四环节');});
await test('57 个技能均可从目录打开',async()=>{await page.goto('http://127.0.0.1:4312/#skills');assert.equal(await page.locator('.skill-link').count(),57);const ids=await page.locator('.skill-link').evaluateAll(as=>as.map(a=>a.hash.split('/')[1]));for(const id of ids){await page.locator(`.skill-link[href="#skills/${id}"]`).click();await page.locator('#skill-detail .skill-code').filter({hasText:'/'+id}).waitFor();assert.ok((await page.locator('#skill-detail').innerText()).includes('能力边界'));}});
await test('搜索 QA 并使用分类筛选，零结果状态可见',async()=>{await page.locator('#skill-search').fill('qa-only');assert.equal(await page.locator('.skill-link').count(),1);await page.locator('#skill-search').fill('不存在的技能__');assert.equal(await page.locator('.skill-link').count(),0);assert.ok(await page.locator('.empty').isVisible());await page.locator('#skill-search').fill('');await page.locator('#skill-group').selectOption({label:'iOS'});assert.equal(await page.locator('.skill-link').count(),5);await page.locator('#skill-group').selectOption('all');await page.locator('#skill-execution').selectOption('method');assert.equal(await page.locator('.skill-link').count(),8);await page.locator('#skill-execution').selectOption('all');});
await test('技能详细页包含输入、产物、三层机制与原文',async()=>{await page.goto('http://127.0.0.1:4312/#skills/review');assert.equal(await page.locator('.mechanism>div').count(),3);assert.equal(await page.locator('.input-output .io').count(),2);await snap('skill-review.png','桌面：review 技能内部原理');});
await test('场景九阶段可切换且实际文档可读取',async()=>{await page.goto('http://127.0.0.1:4312/#scenario');assert.equal(await page.locator('.stage-link').count(),9);await page.locator('a.stage-link[href="#scenario/review"]').click();await page.locator('[data-artifact] summary').click();await page.waitForFunction(()=>document.querySelector('[data-artifact] pre').textContent.includes('ISSUE-001'));assert.ok((await page.locator('article.detail-card').innerText()).includes('20/21'));});
await test('默认重复原库样例产生阻断项',async()=>{await page.goto('http://127.0.0.1:4312/#lab');assert.ok((await page.locator('#lab-result').innerText()).includes('UPSTREAM_DUPLICATE'));await snap('lab-desktop.png','桌面：同一原库重复收录的实际结果');});
await test('配套演示两个目录只计一个原库',async()=>{await page.getByRole('button',{name:'研究 + 配套演示',exact:true}).click();assert.ok((await page.locator('#lab-result').innerText()).includes('本地规则通过'));assert.equal(await page.locator('.result-counts b').nth(0).innerText(),'2');assert.equal(await page.locator('.result-counts b').nth(1).innerText(),'1');});
await test('输入改变后不继续显示旧的通过结论',async()=>{await page.locator('#lab-input').fill('[null]');assert.ok((await page.locator('#lab-result').innerText()).includes('输入已变更'));await page.getByRole('button',{name:'运行检查 →',exact:true}).click();assert.ok((await page.locator('#lab-result').innerText()).includes('ROW_OBJECT'));});
await test('错误 JSON 可恢复，空数组正常处理',async()=>{await page.locator('#lab-input').fill('{');await page.getByRole('button',{name:'运行检查 →',exact:true}).click();assert.ok((await page.locator('#lab-result').innerText()).includes('无法解析'));await page.getByRole('button',{name:'恢复当前样例',exact:true}).click();assert.ok((await page.locator('#lab-result').innerText()).includes('本地规则通过'));await page.locator('#lab-input').fill('[]');await page.getByRole('button',{name:'运行检查 →',exact:true}).click();assert.equal(await page.locator('.result-counts b').nth(0).innerText(),'0');});
await test('无证据发布声明明确报错并保留远程核验提醒',async()=>{await page.getByRole('button',{name:'缺证据的发布声明',exact:true}).click();const t=await page.locator('#lab-result').innerText();assert.ok(t.includes('DEPLOY_URL'));assert.ok(t.includes('DEPLOY_EVIDENCE'));assert.ok(t.includes('REMOTE_UNVERIFIED'));});
await test('用户输入的 HTML 保持为文本，不执行',async()=>{const p={name:'<img src=x onerror="window.injected=true">',researchIndex:'011',directory:'012-test',upstream:'https://github.com/garrytan/gstack',demoStatus:'local'};await page.locator('#lab-input').fill(JSON.stringify([p]));await page.getByRole('button',{name:'运行检查 →',exact:true}).click();assert.equal(await page.evaluate(()=>window.injected),undefined);assert.equal(await page.locator('#lab-result img').count(),0);});
await test('修复后的双斜杠路径在实际界面被拒绝',async()=>{const p={name:'gstack',researchIndex:'011',directory:'012-gstack',upstream:'https://github.com/garrytan//gstack',demoStatus:'local'};await page.locator('#lab-input').fill(JSON.stringify([p]));await page.getByRole('button',{name:'运行检查 →',exact:true}).click();assert.ok((await page.locator('#lab-result').innerText()).includes('UPSTREAM_FORMAT'));});
await test('390px 窄屏可切换输入和运行，没有页面横向溢出',async()=>{await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'同库不同写法',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'运行检查 →',exact:true}).click();assert.ok((await page.locator('#lab-result').innerText()).includes('UPSTREAM_DUPLICATE'));await page.evaluate(()=>scrollTo(0,0));await snap('lab-mobile.png','窄屏：390px 真实检查器界面');});
await test('窄屏技能详情没有横向溢出',async()=>{await page.goto('http://127.0.0.1:4312/#skills/setup-browser-cookies');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);});
await test('200% 文本放大后主要操作仍可达',async()=>{await page.setViewportSize({width:1440,height:1024});await page.goto('http://127.0.0.1:4312/#lab');await page.addStyleTag({content:'body { zoom: 2; }'});assert.ok(await page.getByRole('button',{name:'运行检查 →',exact:true}).isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);});
await test('检查器按钮可通过键盘触发',async()=>{await page.reload();await page.getByRole('button',{name:'合规收录',exact:true}).click();await page.locator('#lab-input').fill('[null]');await page.getByRole('button',{name:'运行检查 →',exact:true}).focus();await page.keyboard.press('Enter');assert.ok((await page.locator('#lab-result').innerText()).includes('ROW_OBJECT'));});
await test('控制台与页面无未处理错误',async()=>assert.deepEqual(errors,[]));
}finally{await browser.close();}
for(const f of fileNames)assert.equal(hash(f),beforeHashes[f],'浏览器验证期间文件被修改：'+f);
const report={kind:'actual-playwright-run',recordedAt:new Date().toISOString(),engine:'Chromium / Playwright',upstreamBrowser:false,origin:'http://127.0.0.1:4312/',total:tests.length,passed:tests.filter(t=>t.status==='passed').length,failed:tests.filter(t=>t.status==='failed').length,files:beforeHashes,tests,screenshots,consoleErrors:errors};
fs.writeFileSync(path.join(root,'evidence/browser.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.failed,failures:tests.filter(t=>t.status==='failed'),screenshots},null,2));process.exitCode=report.failed?1:0;
}
main().catch(e=>{console.error(e);process.exitCode=1;});
