const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const {validate, upstreamKey} = require('../dist/validator.js');
const fixtures = require('../dist/fixtures.js');
const p = fixtures[0].data[0];
const tests = [];
function test(name, fn){const start=performance.now();try{fn();tests.push({name,status:'passed',durationMs:+(performance.now()-start).toFixed(3)});}catch(e){tests.push({name,status:'failed',error:e.message});}}
const codes = x => validate(x).issues.map(i=>i.code);
test('研究索引与历史目录编号允许不同',()=>assert.equal(validate([p]).ok,true));
test('同一原库的配套演示不重复计数',()=>{const r=validate(fixtures[2].data);assert.equal(r.ok,true);assert.equal(r.researchCount,1);});
test('GitHub 大小写、.git、尾斜杠与查询参数归一',()=>assert.equal(upstreamKey(fixtures[1].data[1].upstream),'garrytan/gstack'));
test('同库跨研究索引冲突被发现',()=>assert.ok(codes(fixtures[1].data).includes('UPSTREAM_DUPLICATE')));
test('不同原库不允许同研究索引',()=>assert.ok(codes(fixtures[4].data).includes('INDEX_CONFLICT')));
test('禁止目录路径跳转',()=>assert.ok(codes(fixtures[4].data).includes('DIRECTORY_FORMAT')));
test('同一目录不复用',()=>assert.ok(codes([p,p]).includes('DIRECTORY_DUPLICATE')));
test('已发布记录必须提供地址与证据',()=>{const c=codes(fixtures[3].data);assert.ok(c.includes('DEPLOY_URL'));assert.ok(c.includes('DEPLOY_EVIDENCE'));});
test('字段完整不伪称已完成线上验证',()=>{const r=validate([{...p,demoStatus:'published',demoUrl:'https://example.com/demo',verification:{checkedAt:'2026-09-10T08:00:00Z',commit:'a'.repeat(40)}}]);assert.equal(r.ok,true);assert.ok(r.issues.some(i=>i.code==='REMOTE_UNVERIFIED'));});
test('HTTP 原库地址被拒绝',()=>assert.equal(upstreamKey('http://github.com/a/b'),null));
test('非 GitHub 和带凭据地址被拒绝',()=>{assert.equal(upstreamKey('https://evil.test/a/b'),null);assert.equal(upstreamKey('https://user@github.com/a/b'),null);});
test('仓库子路径与空仓库名被拒绝',()=>{assert.equal(upstreamKey('https://github.com/a/b/tree/main'),null);assert.equal(upstreamKey('https://github.com/a/.git'),null);});
test('空输入数组有效且研究数为零',()=>assert.deepEqual(validate([]),{ok:true,count:0,researchCount:0,issues:[]}));
test('非数组与坏记录给出结构化错误',()=>{assert.equal(validate(null).ok,false);assert.ok(codes([null,1,[]]).every(c=>c==='ROW_OBJECT'));});
test('研究索引按数值而非字符串排序',()=>{const r=validate([{...p,researchIndex:'999'},{...p,researchIndex:'1000',directory:'013-next',upstream:'https://github.com/a/b'}]);assert.ok(!r.issues.some(i=>i.code==='INDEX_ORDER'));});
test('索引倒序提示且不重新分配编号',()=>assert.ok(codes([{...p,researchIndex:'012'},{...p,researchIndex:'011',directory:'013-next',upstream:'https://github.com/a/b'}]).includes('INDEX_ORDER')));
test('无效索引和零目录前缀被拒绝',()=>{assert.ok(codes([{...p,researchIndex:11}]).includes('INDEX_FORMAT'));assert.ok(codes([{...p,directory:'000-zero'}]).includes('DIRECTORY_FORMAT'));});
test('未知状态被拒绝',()=>assert.ok(codes([{...p,demoStatus:'almost-ready'}]).includes('STATUS_INVALID')));
test('截图需要来源说明',()=>assert.ok(codes([{...p,imageKind:'screenshot'}]).includes('IMAGE_EVIDENCE')));
test('大量输入被有界拒绝',()=>assert.equal(validate(Array(2001).fill(p)).issues[0].code,'INPUT_LIMIT'));
test('原库路径中的空层级不能被默默忽略',()=>assert.equal(upstreamKey('https://github.com/garrytan//gstack'),null));
const files=['dist/validator.js','dist/fixtures.js','scripts/test.cjs'];
const hashes=Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',f))).digest('hex')]));
const report={kind:'actual-node-test-run',recordedAt:new Date().toISOString(),runtime:process.version,platform:process.platform,upstreamExecution:false,command:'node scripts/test.cjs',total:tests.length,passed:tests.filter(t=>t.status==='passed').length,failed:tests.filter(t=>t.status==='failed').length,files:hashes,tests};
fs.mkdirSync(path.join(__dirname,'../dist/evidence'),{recursive:true});
fs.writeFileSync(path.join(__dirname,'../dist/evidence/tests.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
process.exitCode=report.failed?1:0;
